name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3

    - name: Cache cargo registry
      id: cache-cargo-registry
      uses: actions/cache@v2
      with:
        path: ~/.cargo
        key: cargo-registry-${{ hashFiles('Cargo.lock') }}
        restore-keys: cargo-registry-

    - name: Build
      run: cargo build --verbose

    - name: Cache cargo registry
      if: always()
      uses: actions/cache@v2
      with:
        path: ~/.cargo
        key: cargo-registry-${{ hashFiles('Cargo.lock') }}

    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Run tests
      run: cargo test --verbose
